customhost = "database-1.cbpstpzjuwa9.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "ngwenxing-employee"
customregion = "us-east-1"
